"""added position table

Revision ID: 532d2eb1879f
Revises: f96beafd5c0c
Create Date: 2024-03-04 15:23:40.017178

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '532d2eb1879f'
down_revision: Union[str, None] = 'f96beafd5c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_positions_id'), 'organization_positions', ['id'], unique=False)
    op.add_column('staff', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staff', 'organization_positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'position_id')
    op.drop_index(op.f('ix_organization_positions_id'), table_name='organization_positions')
    op.drop_table('organization_positions')
    # ### end Alembic commands ###
